#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 11 16:09:38 2020

@author: romeobassobrusa
"""

class Complex:
     def __init__(self, realpart, imagpart):
         self.r = realpart
         self.i = imagpart
        
     def affichage_du_complex(self):
        return self.r+self.i
x = Complex(3.0, -4.5)
y= Complex (2.8,8.0)

print(x.affichage_du_complex())
